/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTomerArgs } from "./CreateTomerArgs";
import { UpdateTomerArgs } from "./UpdateTomerArgs";
import { DeleteTomerArgs } from "./DeleteTomerArgs";
import { TomerFindManyArgs } from "./TomerFindManyArgs";
import { TomerFindUniqueArgs } from "./TomerFindUniqueArgs";
import { Tomer } from "./Tomer";
import { TomerService } from "../tomer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Tomer)
export class TomerResolverBase {
  constructor(
    protected readonly service: TomerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Tomer",
    action: "read",
    possession: "any",
  })
  async _tomersMeta(
    @graphql.Args() args: TomerFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Tomer])
  @nestAccessControl.UseRoles({
    resource: "Tomer",
    action: "read",
    possession: "any",
  })
  async tomers(@graphql.Args() args: TomerFindManyArgs): Promise<Tomer[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Tomer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Tomer",
    action: "read",
    possession: "own",
  })
  async tomer(
    @graphql.Args() args: TomerFindUniqueArgs
  ): Promise<Tomer | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Tomer)
  @nestAccessControl.UseRoles({
    resource: "Tomer",
    action: "create",
    possession: "any",
  })
  async createTomer(@graphql.Args() args: CreateTomerArgs): Promise<Tomer> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Tomer)
  @nestAccessControl.UseRoles({
    resource: "Tomer",
    action: "update",
    possession: "any",
  })
  async updateTomer(
    @graphql.Args() args: UpdateTomerArgs
  ): Promise<Tomer | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Tomer)
  @nestAccessControl.UseRoles({
    resource: "Tomer",
    action: "delete",
    possession: "any",
  })
  async deleteTomer(
    @graphql.Args() args: DeleteTomerArgs
  ): Promise<Tomer | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
